### ISSUE TITLE
Missing Javadoc and code examples make this library difficult to utilize

### ISSUE THREAD

**Issue by jfisher446** [Notronix/JEtsy#1]
Needs Javadoc. Needs examples. 

As a Java developer who also owns an Etsy shop, this library has taken quite a bit of effort and guesswork to get authentication credentials. 

Once I got it to authenticate and store the creds, I found that there doesn't appear to be out-of-the-box support for calling getShop_Transaction, nor several other seller-related endpoints. 

There are no tests to run to ensure that the default methods are working properly, yet the ones that I'm trying are returning 404's.

**Comment by cmunden** [comment]
I have added a "Usage" section to the readme that can be viewed here https://github.com/Notronix/JEtsy/blob/master/README.md

I will close this issue regarding examples.  If you want an issue to stay open regarding javadoc, please feel free to create a new issue indicating that specific request.

If you have any questions at all about using JEtsy then please don't hesitate to ask.  I will do my best to clarify and help you along.
