### ISSUE TITLE
[ISSUE] Personalisation missing?

### ISSUE THREAD

**Issue by gordonturner** [Notronix/JEtsy#4]
First, thanks for sharing this library, looks like it has almost everything I was looking for.

**Describe the bug**
I have a listing that has customization for primary color, secondary color and personalisation.

My understanding is that the variations should have the those values, and indeed there are nodes for 3 values, but are null.

However, looking at etsyTransaction.getListingProduct().getPropertyValues(), I have found the primary color, secondary color values, but have not found the personalisation value.

FYI, I am asking for ShopAssociations.Receipts, ShopAssociations.Transactions, ShopAssociations.Listings, not sure if that has anything to do with it?

**To Reproduce**
Sample code here:
https://gist.github.com/gordonturner/d0b0333403aaa1daaa128294e827005f
https://gist.github.com/gordonturner/89ad05a8eb48c94fa75d0e66efe1a47a

It is a work in progress, so it is a little rough.

**Expected behavior**
The variations should have the primary color, secondary color and personalisation.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Version: 1.0.0012

**Smartphone (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by gordonturner** [comment]
Hey @cmunden just to follow up, did some more debugging.

My request to Esty (after authenticating) was for:

```java
etsyDataService.getShop(accessCredentials,  shopIdsOrNames,
                    ShopAssociations.Receipts,
                    ShopAssociations.Transactions,
                    ShopAssociations.Listings,
                    ShopAssociations.User)
```

I put a breakpoint on EtsyDataService.java line 391 to see the response back from Esty.

(https://github.com/Notronix/JEtsy/blob/master/src/main/java/com/notronix/etsy/impl/EtsyDataService.java#L391)

In the raw response, I can see the variations:

<img width="706" alt="2-response-value" src="https://user-images.githubusercontent.com/705523/118282941-d0729480-b49c-11eb-9c8c-f0b4f76362ad.png">

However when I hit the breakpoint I see the correct total number of variations in the array (three), but they are empty.

Additionally, looking closer at the object in the variations array, the type is **EtsyListingInventory**, which I don't think is correct.

<img width="462" alt="3-object-debug-value" src="https://user-images.githubusercontent.com/705523/118283208-1b8ca780-b49d-11eb-980e-fdd574477406.png">

I am going to try and dig into how the variations are set / deserialized.

Thanks,
Gord.

**Comment by cmunden** [comment]
Version 2 of the API has been turned off.  Now moving the implementation to Version 3.
